-- MySQL Script generated by MySQL Workbench
-- Wed Nov 16 00:53:55 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema stajdurumlari
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema stajdurumlari
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stajdurumlari` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `stajdurumlari` ;

-- -----------------------------------------------------
-- Table `stajdurumlari`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stajdurumlari`.`admin` (
                                                       `Admin_ID`  NOT NULL,
                                                       `Admin_UserName` VARCHAR(40) NULL DEFAULT NULL,
    `Admin_Password` VARCHAR(50) NULL DEFAULT NULL,
    `Admin_Mail` VARCHAR(100) NULL DEFAULT NULL,
    PRIMARY KEY (`Admin_ID`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stajdurumlari`.`teachers_informations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stajdurumlari`.`teachers_informations` (
                                                                       `Teacher_ID`  NOT NULL,
                                                                       `Teacher_Number` VARCHAR(6) NOT NULL,
    `Teacher_Name` VARCHAR(25) NULL DEFAULT NULL,
    `Teacher_SurName` VARCHAR(25) NULL DEFAULT NULL,
    `commission_memberShip` VARCHAR(1) NULL DEFAULT NULL,
    `Teacher_mail` VARCHAR(100) NOT NULL,
    `Teacher_password` VARCHAR(50) NOT NULL,
    PRIMARY KEY (`Teacher_ID`),
    UNIQUE INDEX `Teacher_Number` (`Teacher_Number` ASC) VISIBLE)
    ENGINE = InnoDB
    AUTO_INCREMENT = 2
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stajdurumlari`.`commissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stajdurumlari`.`commissions` (
                                                             `Commission_ID`  NOT NULL,
                                                             `Teacher_Number` VARCHAR(25) NULL DEFAULT NULL,
    `Teacher_ID`  NOT NULL,
    PRIMARY KEY (`Commission_ID`),
    INDEX `Teacher_Number` (`Teacher_Number` ASC) VISIBLE,
    INDEX `Teacher_ID` (`Teacher_ID` ASC) VISIBLE,
    CONSTRAINT `commissions_ibfk_1`
    FOREIGN KEY (`Teacher_Number`)
    REFERENCES `stajdurumlari`.`teachers_informations` (`Teacher_Number`),
    CONSTRAINT `commissions_ibfk_2`
    FOREIGN KEY (`Teacher_ID`)
    REFERENCES `stajdurumlari`.`teachers_informations` (`Teacher_ID`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stajdurumlari`.`commissions_logininformations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stajdurumlari`.`commissions_logininformations` (
                                                                               `COMISSION_ID`  NOT NULL,
                                                                               `COMISSION_PASSWORD` VARCHAR(50) NULL DEFAULT NULL,
    INDEX `COMISSION_ID` (`COMISSION_ID` ASC) VISIBLE,
    CONSTRAINT `commissions_logininformations_ibfk_1`
    FOREIGN KEY (`COMISSION_ID`)
    REFERENCES `stajdurumlari`.`commissions` (`Commission_ID`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stajdurumlari`.`company_informations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stajdurumlari`.`company_informations` (
                                                                      `Company_ID`  NOT NULL,
                                                                      `Company_Name` VARCHAR(150) NOT NULL,
    `Activity_Field` VARCHAR(50) NOT NULL,
    `Company_adress` VARCHAR(300) NOT NULL,
    `Company_city` VARCHAR(25) NOT NULL,
    `Company_town` VARCHAR(25) NOT NULL,
    `Company_postCode` VARCHAR(5) NULL DEFAULT NULL,
    `Company_PhoneNumber` VARCHAR(15) NULL DEFAULT NULL,
    `Company_FAX` VARCHAR(50) NULL DEFAULT NULL,
    `Company_mailAdress` VARCHAR(120) NULL DEFAULT NULL,
    `Responsible_Title` VARCHAR(1) NULL DEFAULT NULL,
    `Law_3308` VARCHAR(1) NULL DEFAULT NULL,
    `st_id`  NULL DEFAULT NULL,
    UNIQUE INDEX `Company_ID` (`Company_ID` ASC) VISIBLE,
    UNIQUE INDEX `Company_PhoneNumber` (`Company_PhoneNumber` ASC) VISIBLE)
    ENGINE = InnoDB
    AUTO_INCREMENT = 12
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stajdurumlari`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stajdurumlari`.`students` (
                                                          `st_id`  NOT NULL,
                                                          `st_name` VARCHAR(25) NOT NULL,
    `st_lastName` VARCHAR(25) NOT NULL,
    `st_TC_No` VARCHAR(11) NOT NULL,
    `st_PhoneNumber` VARCHAR(11) NOT NULL,
    `st_mailAdress` VARCHAR(120) NOT NULL,
    `st_class` VARCHAR(1) NOT NULL,
    `st_adress` VARCHAR(300) NOT NULL,
    `st_city` VARCHAR(25) NOT NULL,
    `st_town` VARCHAR(25) NOT NULL,
    `st_postCode` VARCHAR(5) NOT NULL,
    `st_citizenship` VARCHAR(15) NOT NULL,
    `st_Teacher_ID`  NOT NULL,
    `st_faculty` VARCHAR(70) NULL DEFAULT NULL,
    `st_department` VARCHAR(70) NULL DEFAULT NULL,
    `st_password` VARCHAR(60) NOT NULL,
    `st_IS_info` VARCHAR(1) NULL DEFAULT NULL,
    PRIMARY KEY (`st_id`),
    UNIQUE INDEX `st_TC_No` (`st_TC_No` ASC) VISIBLE,
    UNIQUE INDEX `st_PhoneNumber` (`st_PhoneNumber` ASC) VISIBLE,
    INDEX `st_Teacher_ID` (`st_Teacher_ID` ASC) VISIBLE,
    CONSTRAINT `students_ibfk_1`
    FOREIGN KEY (`st_Teacher_ID`)
    REFERENCES `stajdurumlari`.`teachers_informations` (`Teacher_ID`))
    ENGINE = InnoDB
    AUTO_INCREMENT = 42
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stajdurumlari`.`internship_application`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stajdurumlari`.`internship_application` (
                                                                        `st_id`  NOT NULL,
                                                                        `Company_ID` VARCHAR(5) NOT NULL,
    `Internship_ID` VARCHAR(15) NOT NULL,
    `starting_date` DATE NULL DEFAULT NULL,
    `finish_date` DATE NULL DEFAULT NULL,
    `Company_Name` VARCHAR(150) NULL DEFAULT NULL,
    `working_day` VARCHAR(2) NULL DEFAULT NULL,
    `saturday_working` VARCHAR(1) NULL DEFAULT NULL,
    `Activity_Field` VARCHAR(50) NULL DEFAULT NULL,
    `Company_adress` VARCHAR(300) NOT NULL,
    `Company_city` VARCHAR(25) NOT NULL,
    `Company_town` VARCHAR(25) NOT NULL,
    `Company_postCode` VARCHAR(5) NOT NULL,
    `Company_PhoneNumber` VARCHAR(15) NOT NULL,
    `Company_FAX` VARCHAR(50) NOT NULL,
    `Company_mailAdress` VARCHAR(120) NOT NULL,
    `Responsible_Title` VARCHAR(1) NOT NULL,
    `health_care` VARCHAR(1) NULL DEFAULT NULL,
    `GSS` VARCHAR(1) NULL DEFAULT NULL,
    `yearOld_25` VARCHAR(1) NULL DEFAULT NULL,
    `law_3308` VARCHAR(1) NOT NULL,
    `application_complete` VARCHAR(1) NULL DEFAULT NULL,
    PRIMARY KEY (`Internship_ID`),
    UNIQUE INDEX `Company_PhoneNumber` (`Company_PhoneNumber` ASC) VISIBLE,
    INDEX `st_id` (`st_id` ASC) VISIBLE,
    CONSTRAINT `internship_application_ibfk_1`
    FOREIGN KEY (`st_id`)
    REFERENCES `stajdurumlari`.`students` (`st_id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stajdurumlari`.`internship_informations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stajdurumlari`.`internship_informations` (
                                                                         `IS_ID`  NOT NULL,
                                                                         `Company_ID`  NOT NULL,
                                                                         `st_id`  NOT NULL,
                                                                         `starting_date` DATE NULL DEFAULT NULL,
                                                                         `finish_date` DATE NULL DEFAULT NULL,
                                                                         `working_day` VARCHAR(2) NULL DEFAULT NULL,
    `saturday_working` VARCHAR(1) NULL DEFAULT NULL,
    `healt_care` VARCHAR(1) NULL DEFAULT NULL,
    `GSS` VARCHAR(1) NULL DEFAULT NULL,
    `old_25` VARCHAR(1) NULL DEFAULT NULL,
    `intern_ship_level` VARCHAR(1) NOT NULL,
    UNIQUE INDEX `IS_ID` (`IS_ID` ASC) VISIBLE,
    INDEX `Company_ID` (`Company_ID` ASC) VISIBLE,
    INDEX `st_id` (`st_id` ASC) VISIBLE,
    CONSTRAINT `internship_informations_ibfk_1`
    FOREIGN KEY (`Company_ID`)
    REFERENCES `stajdurumlari`.`company_informations` (`Company_ID`),
    CONSTRAINT `internship_informations_ibfk_2`
    FOREIGN KEY (`st_id`)
    REFERENCES `stajdurumlari`.`students` (`st_id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stajdurumlari`.`teachers_logininformations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stajdurumlari`.`teachers_logininformations` (
                                                                            `Teacher_password` TEXT NOT NULL,
                                                                            `Teacher_ID`  NOT NULL,
                                                                            INDEX `Teacher_ID` (`Teacher_ID` ASC) VISIBLE,
    CONSTRAINT `teachers_logininformations_ibfk_1`
    FOREIGN KEY (`Teacher_ID`)
    REFERENCES `stajdurumlari`.`teachers_informations` (`Teacher_ID`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stajdurumlari`.`test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stajdurumlari`.`test` (
    `id`  NULL DEFAULT NULL)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
